/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package staffmanagement.GUI.dialog.department;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import staffmanagement.BUS.EmployeeBUS;
import staffmanagement.BUS.EntityType;
import staffmanagement.DTO.Department;
import staffmanagement.DTO.Employee;
import staffmanagement.GUI.MainPageGUI;
import staffmanagement.GUI.dialog.employee.AddEmployeeDialogGUI;
import staffmanagement.GUI.dialog.employee.EditEmployeeDialogGUI;

/**
 *
 * @author Admin
 */
public class ListEmpDepartmentDialogGUI extends javax.swing.JDialog
        implements ActionListener {

    private MainPageGUI parent;
    private Department department;
    private EmployeeBUS employeeBUS;
    private DefaultTableModel tableModel;

    /**
     * Creates new form EmpDepartmentFrm
     */
    public ListEmpDepartmentDialogGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (MainPageGUI) parent;
        department = getDepartment();
        employeeBUS = new EmployeeBUS();
        employeeBUS.addAll(department.getEmpList());
        tableModel = (DefaultTableModel) tableEmployee.getModel();
        refreshEmployee(employeeBUS.getList());
        setInfomation();
        addActionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        labelList = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelSize = new javax.swing.JLabel();
        txtIdDepartment = new javax.swing.JLabel();
        txtNameDepartment = new javax.swing.JLabel();
        txtSizeDepartment = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        boxSearchOption = new javax.swing.JComboBox<>();
        panelTask = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Lương cơ bản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEmployee);

        labelList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelList.setText("DANH SÁCH");

        btnRefresh.setText("Làm mới");

        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        labelId.setText("Mã phòng ban:");

        labelName.setText("Tên phòng ban:");

        labelSize.setText("Số lượng nhân viên:");

        txtIdDepartment.setText("Mã");

        txtNameDepartment.setText("Tên");

        txtSizeDepartment.setText("Số lượng");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(labelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSizeDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(txtIdDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(txtIdDepartment))
                .addGap(24, 24, 24)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtNameDepartment))
                .addGap(24, 24, 24)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSize)
                    .addComponent(txtSizeDepartment))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        btnSearch.setText("Tìm");

        boxSearchOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo mã nhân viên", "Theo họ tên" }));

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearch)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(boxSearchOption, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSearchOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap())
        );

        panelTask.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ"));

        btnAdd.setText("Thêm");

        btnEdit.setText("Xem/Sửa");

        btnRemove.setText("Xóa");

        javax.swing.GroupLayout panelTaskLayout = new javax.swing.GroupLayout(panelTask);
        panelTask.setLayout(panelTaskLayout);
        panelTaskLayout.setHorizontalGroup(
            panelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTaskLayout.createSequentialGroup()
                        .addComponent(btnRemove)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTaskLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(14, 14, 14))))
        );
        panelTaskLayout.setVerticalGroup(
            panelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnRemove)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenu1.add(jSeparator1);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/file-exit.png"))); // NOI18N
        menuItemExit.setText("Thoát");
        jMenu1.add(menuItemExit);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(panelTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(labelList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListEmpDepartmentDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListEmpDepartmentDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListEmpDepartmentDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListEmpDepartmentDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListEmpDepartmentDialogGUI dialog = new ListEmpDepartmentDialogGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSearchOption;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelList;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSize;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelTask;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JLabel txtIdDepartment;
    private javax.swing.JLabel txtNameDepartment;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtSizeDepartment;
    // End of variables declaration//GEN-END:variables

    public Department getDepartment() {
        var index = parent.getIndexSelected(EntityType.DEP);
        var departmentTmp = parent.getDepartmentBus().getList().get(index);
        return departmentTmp;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnAdd)) {
            AddEmployeeDialogGUI addEmployeeDialogGUI
                    = new AddEmployeeDialogGUI(parent, rootPaneCheckingEnabled, true);
            addEmployeeDialogGUI.setLocationRelativeTo(null);
            addEmployeeDialogGUI.setVisible(rootPaneCheckingEnabled);
            department = getDepartment();
            employeeBUS.removeAll();
            employeeBUS.addAll(department.getEmpList());
            setInfomation();
            refreshEmployee(employeeBUS.getList());
        }
        if (obj.equals(btnRemove)) {
            removeAction();
            refreshEmployee(employeeBUS.getList());
        }
        if (obj.equals(btnEdit)) {
            var index = tableEmployee.getSelectedRow();
            var tableListEmpModel = tableModel;
            EditEmployeeDialogGUI editEmployeeDialogGUI
                    = new EditEmployeeDialogGUI(parent, rootPaneCheckingEnabled
                            , true, index, tableListEmpModel, employeeBUS);
            editEmployeeDialogGUI.setLocationRelativeTo(null);
            editEmployeeDialogGUI.setVisible(rootPaneCheckingEnabled);
            refreshEmployee(employeeBUS.getList());
        }
        if (obj.equals(btnSearch)) {
            if(!employeeBUS.isEmpty()){
                int choice = boxSearchOption.getSelectedIndex();
                switch(choice){
                    case 0->{
                        var id = txtSearch.getText();
                        var emp = employeeBUS.findById(id);
                        if(emp!=null){
                            tableModel.setRowCount(0);
                            showEmployee(emp);
                        }
                        else{
                            var msg = "Không tìm thấy";
                            showMessage(msg);
                        }
                    }
                    case 1->{
                        var name = txtSearch.getText();
                        var empList = employeeBUS.findByName(name);
                        if(!empList.isEmpty()){
                            refreshEmployee(empList);
                        }
                        else{
                            var msg = "Không tìm thấy";
                            showMessage(msg);
                        }
                    }
                }
            }
        }
        if (obj.equals(btnRefresh)) {
            refreshEmployee(employeeBUS.getList());
        }
        if(obj.equals(menuItemExit)){
            this.dispose();
        }
    }

    private void addActionListener() {
        //task
        btnAdd.addActionListener(this);
        btnRemove.addActionListener(this);
        btnEdit.addActionListener(this);

        //search
        btnSearch.addActionListener(this);

        //refresh
        btnRefresh.addActionListener(this);

        //menu
        menuItemExit.addActionListener(this);
    }

    private void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    private void setInfomation() {
        this.setTitle("Danh sách phòng ban "
                + department.getName().toUpperCase());
        txtIdDepartment.setText(department.getId());
        txtNameDepartment.setText(department.getName());
        int size = department.getEmpList().size();
        txtSizeDepartment.setText(size + "");
    }

    private void removeAction() {
        if (!employeeBUS.isEmpty()) {
            var index = tableEmployee.getSelectedRow();
            if (index > -1) {
                var obj = employeeBUS.getList().get(index);
                var choice = JOptionPane.showConfirmDialog(parent,
                         "Bạn có chắc chắn muốn xóa?");
                if (choice == 0) {
                    if (employeeBUS.remove(obj)) {
                        var msg = "Xóa thành công";
                        showMessage(msg);
                    }
                }
            } else {
                var msg = "Hãy chọn 1 dòng";
                showMessage(msg);
            }
        }
    }
    
    private void refreshEmployee(List<Employee> list) {
        tableModel.setRowCount(0);
        for (Employee obj : list) {
            showEmployee(obj);
        }
    }
    
    public void showEmployee(Employee emp) {
        var row = new Object[]{emp.getId(),
            emp.getFullName(), emp.getPosition(), emp.getBaseSalary()};
        tableModel.addRow(row);
        tableModel.fireTableDataChanged();
    }
}
