/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staffmanagement.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import staffmanagement.BUS.BUS;
import staffmanagement.BUS.DepartmentBUS;
import staffmanagement.BUS.EmployeeBUS;
import staffmanagement.BUS.EntityType;
import staffmanagement.BUS.SaveType;
import staffmanagement.BUS.filter.DataFilter;
import staffmanagement.DTO.Department;
import staffmanagement.DTO.Employee;
import staffmanagement.GUI.dialog.department.AddDepartmentGUI;
import staffmanagement.GUI.dialog.department.EditDepartmentDialogGUI;
import staffmanagement.GUI.dialog.department.InfoDialogGUI;
import staffmanagement.GUI.dialog.department.ListEmpDepartmentDialogGUI;
import staffmanagement.GUI.dialog.employee.AddEmployeeDialogGUI;
import staffmanagement.GUI.dialog.employee.EditEmployeeDialogGUI;
import staffmanagement.GUI.dialog.employee.InfoEmployeeDialogGUI;

/**
 *
 * @author Admin
 */
public class MainPageGUI extends javax.swing.JFrame implements ActionListener {

    private DefaultTableModel tableModelDepartment;
    private DefaultTableModel tableModelEmployee;
    private final DepartmentBUS departmentBus;
    private final EmployeeBUS employeeBus;
    private String defaultFileName;
    private boolean flagSaveStatus = true;
    private EntityType entityType;

    /**
     * Creates new form StaffManagementGUI
     */
    public MainPageGUI() {
        initComponents();
        setLocationRelativeTo(null);
        tableModelDepartment = (DefaultTableModel) tableDepartment.getModel();
        tableModelEmployee = (DefaultTableModel) tableEmployee.getModel();
        departmentBus = new DepartmentBUS();
        employeeBus = new EmployeeBUS();
        addActionListener();
        addBtnGroupDepartment();
        addBtnGroupEmployee();
    }

    public DepartmentBUS getDepartmentBus() {
        return departmentBus;
    }

    public EmployeeBUS getEmployeeBus() {
        return employeeBus;
    }

    public int getIndexSelected(EntityType entityType) {
        int index = -1;
        switch (entityType) {
            case EntityType.DEP -> {
                index = tableDepartment.getSelectedRow();

            }
            case EntityType.EMP -> {
                index = tableEmployee.getSelectedRow();
            }
        }
        return index;
    }

    public DefaultTableModel getTableModel(EntityType entityType) {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        switch (entityType) {
            case EntityType.DEP -> {
                defaultTableModel = tableModelDepartment;
            }
            case EntityType.EMP -> {
                defaultTableModel = tableModelEmployee;
            }
        }
        return defaultTableModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSortDep = new javax.swing.ButtonGroup();
        groupSortEmp = new javax.swing.ButtonGroup();
        tabPane = new javax.swing.JTabbedPane();
        panelDepartment = new javax.swing.JPanel();
        labelNameDepartment = new javax.swing.JLabel();
        labelIconDepartment = new javax.swing.JLabel();
        scrollPaneTableDepartment = new javax.swing.JScrollPane();
        tableDepartment = new javax.swing.JTable();
        panelSearchDepartment = new javax.swing.JPanel();
        lbDepartmentId = new javax.swing.JLabel();
        txtDepartmentId = new javax.swing.JTextField();
        btnSearchDepartment = new javax.swing.JButton();
        panelSortDepartment = new javax.swing.JPanel();
        rdbSortByNameDepartmentASC = new javax.swing.JRadioButton();
        rdbSortByMemberSizeDESC = new javax.swing.JRadioButton();
        rdbSortByMemberSizeASC = new javax.swing.JRadioButton();
        panelTaskDepartment = new javax.swing.JPanel();
        btnAddDepartment = new javax.swing.JButton();
        btnEditDepartment = new javax.swing.JButton();
        btnDelDepartment = new javax.swing.JButton();
        btnListEmpDepartment = new javax.swing.JButton();
        btnRefreshDepartment = new javax.swing.JButton();
        panelEmployee = new javax.swing.JPanel();
        labelIconEmployee = new javax.swing.JLabel();
        labelEmployee = new javax.swing.JLabel();
        panelSearchEmployee = new javax.swing.JPanel();
        txtEmployeeSearch = new javax.swing.JTextField();
        boxSearch = new javax.swing.JComboBox<>();
        btnSearchEmployee = new javax.swing.JButton();
        panelTaskEmployee = new javax.swing.JPanel();
        btnAddEmployee = new javax.swing.JButton();
        btnDelEmployee = new javax.swing.JButton();
        btnEditEmployee = new javax.swing.JButton();
        btnInfoEmployee = new javax.swing.JButton();
        panelSortEmployee = new javax.swing.JPanel();
        rdbSortByNameASC = new javax.swing.JRadioButton();
        rdbSortBySalaryASC = new javax.swing.JRadioButton();
        rdbSortBySalaryDESC = new javax.swing.JRadioButton();
        btnRefreshEmployee = new javax.swing.JButton();
        scrollPaneTableEmployee = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        btnExportEmp = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        btnOpen = new javax.swing.JMenuItem();
        btnSave = new javax.swing.JMenuItem();
        btnSaveAs = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        btnExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí nhân sự");
        setResizable(false);

        panelDepartment.setPreferredSize(new java.awt.Dimension(604, 440));

        labelNameDepartment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNameDepartment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNameDepartment.setText("PHÒNG BAN TINIWORLD");

        labelIconDepartment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tiniworld.png"))); // NOI18N

        tableDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng ban", "Tên phòng ban", "Số lượng nhân viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTableDepartment.setViewportView(tableDepartment);

        panelSearchDepartment.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        lbDepartmentId.setText("Mã phòng ban:");

        btnSearchDepartment.setText("Tìm");

        javax.swing.GroupLayout panelSearchDepartmentLayout = new javax.swing.GroupLayout(panelSearchDepartment);
        panelSearchDepartment.setLayout(panelSearchDepartmentLayout);
        panelSearchDepartmentLayout.setHorizontalGroup(
            panelSearchDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSearchDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchDepartment)
                    .addComponent(txtDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelSearchDepartmentLayout.setVerticalGroup(
            panelSearchDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartmentId)
                    .addComponent(txtDepartmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchDepartment)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelSortDepartment.setBorder(javax.swing.BorderFactory.createTitledBorder("Sắp xếp"));

        rdbSortByNameDepartmentASC.setText("Theo chữ cái A-Z");

        rdbSortByMemberSizeDESC.setText("Theo số lượng nhân viên giảm dần");

        rdbSortByMemberSizeASC.setText("Theo số lượng nhân viên tăng dần");

        javax.swing.GroupLayout panelSortDepartmentLayout = new javax.swing.GroupLayout(panelSortDepartment);
        panelSortDepartment.setLayout(panelSortDepartmentLayout);
        panelSortDepartmentLayout.setHorizontalGroup(
            panelSortDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSortDepartmentLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelSortDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbSortByNameDepartmentASC, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbSortByMemberSizeDESC)
                    .addComponent(rdbSortByMemberSizeASC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSortDepartmentLayout.setVerticalGroup(
            panelSortDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSortDepartmentLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(rdbSortByMemberSizeASC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbSortByMemberSizeDESC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbSortByNameDepartmentASC)
                .addContainerGap())
        );

        panelTaskDepartment.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ"));

        btnAddDepartment.setText("Thêm");

        btnEditDepartment.setText("Sửa");

        btnDelDepartment.setText("Xóa");

        btnListEmpDepartment.setText("DSNV");

        javax.swing.GroupLayout panelTaskDepartmentLayout = new javax.swing.GroupLayout(panelTaskDepartment);
        panelTaskDepartment.setLayout(panelTaskDepartmentLayout);
        panelTaskDepartmentLayout.setHorizontalGroup(
            panelTaskDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskDepartmentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelTaskDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTaskDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListEmpDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelTaskDepartmentLayout.setVerticalGroup(
            panelTaskDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTaskDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDepartment)
                    .addComponent(btnEditDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTaskDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelDepartment)
                    .addComponent(btnListEmpDepartment))
                .addGap(79, 79, 79))
        );

        btnRefreshDepartment.setText("Làm mới");

        javax.swing.GroupLayout panelDepartmentLayout = new javax.swing.GroupLayout(panelDepartment);
        panelDepartment.setLayout(panelDepartmentLayout);
        panelDepartmentLayout.setHorizontalGroup(
            panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNameDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelDepartmentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSearchDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSortDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTaskDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshDepartment, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
            .addGroup(panelDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTableDepartment)
                .addContainerGap())
            .addGroup(panelDepartmentLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(labelIconDepartment)
                .addGap(219, 219, 219))
        );
        panelDepartmentLayout.setVerticalGroup(
            panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartmentLayout.createSequentialGroup()
                .addComponent(labelIconDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNameDepartment)
                .addGap(18, 18, 18)
                .addGroup(panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTaskDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(panelSearchDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDepartmentLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnRefreshDepartment))
                    .addGroup(panelDepartmentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelSortDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneTableDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPane.addTab("DS Phòng ban", panelDepartment);

        labelIconEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tiniworld.png"))); // NOI18N

        labelEmployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmployee.setText("NHÂN VIÊN TINIWORLD");

        panelSearchEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        boxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo mã nhân viên", "Theo tên nhân viên" }));

        btnSearchEmployee.setText("Tìm kiếm");

        javax.swing.GroupLayout panelSearchEmployeeLayout = new javax.swing.GroupLayout(panelSearchEmployee);
        panelSearchEmployee.setLayout(panelSearchEmployeeLayout);
        panelSearchEmployeeLayout.setHorizontalGroup(
            panelSearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmployeeSearch)
                    .addGroup(panelSearchEmployeeLayout.createSequentialGroup()
                        .addComponent(boxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnSearchEmployee)))
                .addContainerGap())
        );
        panelSearchEmployeeLayout.setVerticalGroup(
            panelSearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchEmployeeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(txtEmployeeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchEmployee))
                .addGap(18, 18, 18))
        );

        panelTaskEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder("Tác vụ"));

        btnAddEmployee.setText("Thêm");

        btnDelEmployee.setText("Xóa");

        btnEditEmployee.setText("Sửa");

        btnInfoEmployee.setText("Thông tin");

        javax.swing.GroupLayout panelTaskEmployeeLayout = new javax.swing.GroupLayout(panelTaskEmployee);
        panelTaskEmployee.setLayout(panelTaskEmployeeLayout);
        panelTaskEmployeeLayout.setHorizontalGroup(
            panelTaskEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTaskEmployeeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelTaskEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panelTaskEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInfoEmployee, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        panelTaskEmployeeLayout.setVerticalGroup(
            panelTaskEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTaskEmployeeLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelTaskEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelEmployee)
                    .addComponent(btnAddEmployee))
                .addGap(18, 18, 18)
                .addGroup(panelTaskEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditEmployee)
                    .addComponent(btnInfoEmployee))
                .addGap(14, 14, 14))
        );

        panelSortEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder("Sắp xếp"));

        rdbSortByNameASC.setText("Sắp xếp theo tên A-Z");

        rdbSortBySalaryASC.setText("Sắp xếp theo lương tăng dần");

        rdbSortBySalaryDESC.setText("Sắp xếp theo lương giảm dần");

        javax.swing.GroupLayout panelSortEmployeeLayout = new javax.swing.GroupLayout(panelSortEmployee);
        panelSortEmployee.setLayout(panelSortEmployeeLayout);
        panelSortEmployeeLayout.setHorizontalGroup(
            panelSortEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSortEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSortEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSortEmployeeLayout.createSequentialGroup()
                        .addComponent(rdbSortBySalaryASC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(panelSortEmployeeLayout.createSequentialGroup()
                        .addGroup(panelSortEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbSortByNameASC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbSortBySalaryDESC))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelSortEmployeeLayout.setVerticalGroup(
            panelSortEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSortEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbSortByNameASC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbSortBySalaryASC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbSortBySalaryDESC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRefreshEmployee.setText("Làm mới");

        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Vị trí", "Lương cơ bản"
            }
        ));
        scrollPaneTableEmployee.setViewportView(tableEmployee);

        btnExportEmp.setText("Xuất DSNV");

        javax.swing.GroupLayout panelEmployeeLayout = new javax.swing.GroupLayout(panelEmployee);
        panelEmployee.setLayout(panelEmployeeLayout);
        panelEmployeeLayout.setHorizontalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(labelIconEmployee)
                        .addGap(0, 217, Short.MAX_VALUE))
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneTableEmployee)))
                .addContainerGap())
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSearchEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSortEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTaskEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                        .addComponent(btnExportEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshEmployee)))
                .addGap(17, 17, 17))
        );
        panelEmployeeLayout.setVerticalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addComponent(labelIconEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEmployeeLayout.createSequentialGroup()
                        .addComponent(labelEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelTaskEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelSortEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefreshEmployee)
                        .addComponent(btnExportEmp)))
                .addGap(12, 12, 12)
                .addComponent(scrollPaneTableEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPane.addTab("DS Nhân viên", panelEmployee);

        menuFile.setText("File");

        btnOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/file-open.png"))); // NOI18N
        btnOpen.setText("Mở");
        menuFile.add(btnOpen);

        btnSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/file-save.png"))); // NOI18N
        btnSave.setText("Lưu");
        menuFile.add(btnSave);

        btnSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/file-save-as.png"))); // NOI18N
        btnSaveAs.setText("Lưu mới");
        menuFile.add(btnSaveAs);
        menuFile.add(separator);

        btnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/file-exit.png"))); // NOI18N
        btnExit.setText("Thoát");
        menuFile.add(btnExit);

        menuBar.add(menuFile);

        menuEdit.setText("Thông tin");

        menuItemInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/info.png"))); // NOI18N
        menuItemInfo.setText("Thông tin");
        menuEdit.add(menuItemInfo);

        menuBar.add(menuEdit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSearch;
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnDelDepartment;
    private javax.swing.JButton btnDelEmployee;
    private javax.swing.JButton btnEditDepartment;
    private javax.swing.JButton btnEditEmployee;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JButton btnExportEmp;
    private javax.swing.JButton btnInfoEmployee;
    private javax.swing.JButton btnListEmpDepartment;
    private javax.swing.JMenuItem btnOpen;
    private javax.swing.JButton btnRefreshDepartment;
    private javax.swing.JButton btnRefreshEmployee;
    private javax.swing.JMenuItem btnSave;
    private javax.swing.JMenuItem btnSaveAs;
    private javax.swing.JButton btnSearchDepartment;
    private javax.swing.JButton btnSearchEmployee;
    private javax.swing.ButtonGroup groupSortDep;
    private javax.swing.ButtonGroup groupSortEmp;
    private javax.swing.JLabel labelEmployee;
    private javax.swing.JLabel labelIconDepartment;
    private javax.swing.JLabel labelIconEmployee;
    private javax.swing.JLabel labelNameDepartment;
    private javax.swing.JLabel lbDepartmentId;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemInfo;
    private javax.swing.JPanel panelDepartment;
    private javax.swing.JPanel panelEmployee;
    private javax.swing.JPanel panelSearchDepartment;
    private javax.swing.JPanel panelSearchEmployee;
    private javax.swing.JPanel panelSortDepartment;
    private javax.swing.JPanel panelSortEmployee;
    private javax.swing.JPanel panelTaskDepartment;
    private javax.swing.JPanel panelTaskEmployee;
    private javax.swing.JRadioButton rdbSortByMemberSizeASC;
    private javax.swing.JRadioButton rdbSortByMemberSizeDESC;
    private javax.swing.JRadioButton rdbSortByNameASC;
    private javax.swing.JRadioButton rdbSortByNameDepartmentASC;
    private javax.swing.JRadioButton rdbSortBySalaryASC;
    private javax.swing.JRadioButton rdbSortBySalaryDESC;
    private javax.swing.JScrollPane scrollPaneTableDepartment;
    private javax.swing.JScrollPane scrollPaneTableEmployee;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tableDepartment;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JTextField txtDepartmentId;
    private javax.swing.JTextField txtEmployeeSearch;
    // End of variables declaration//GEN-END:variables

    public void showDepartment(Department dep) {
        var row = new Object[]{dep.getId(),
            dep.getName(), dep.getEmpList().size()};
        tableModelDepartment.addRow(row);
        tableModelDepartment.fireTableDataChanged();
    }

    private void addActionListener() {
        addActionListenerDeparment();
        addActionListenerEmployee();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        actionPerformedDeparment(e);
        actionPerformedEmployee(e);
    }

    public void actionPerformedDeparment(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnAddDepartment)) {
            AddDepartmentGUI addDepartmentDialog
                    = new AddDepartmentGUI(this, rootPaneCheckingEnabled);
            addDepartmentDialog.setLocationRelativeTo(null);
            addDepartmentDialog.setVisible(rootPaneCheckingEnabled);
            flagSaveStatus = false;
        }
        if (obj.equals(btnEditDepartment)) {
            editAction(departmentBus, EntityType.DEP);
        }
        if (obj.equals(btnListEmpDepartment)) {
            if (!departmentBus.isEmpty()) {
                var index = tableDepartment.getSelectedRow();
                if (index != -1) {
                    ListEmpDepartmentDialogGUI edf
                            = new ListEmpDepartmentDialogGUI(this,
                                    rootPaneCheckingEnabled);
                    edf.setLocationRelativeTo(null);
                    edf.setVisible(rootPaneCheckingEnabled);
                    refreshDepartment(departmentBus.getList());
                    flagSaveStatus = false;
                } else {
                    var msg = "Hãy chọn 1 phòng ban!";
                    showMessage(msg);
                }
            } else {
                var msg = "Danh sách phòng ban rỗng.";
                showMessage(msg);
            }
        }
        if (obj.equals(btnDelDepartment)) {
            deleteAction(departmentBus, EntityType.DEP);
            flagSaveStatus = false;
        }
        if (obj.equals(btnSearchDepartment)) {
            findAction(departmentBus, EntityType.DEP);
        }
        if (obj.equals(rdbSortByNameDepartmentASC)
                || obj.equals(rdbSortByMemberSizeASC)
                || obj.equals(rdbSortByMemberSizeDESC)) {
            sortDepartment(obj);
            flagSaveStatus = false;
        }
        if (obj.equals(btnRefreshDepartment)) {
            List<Department> list = departmentBus.getList();
            refreshDepartment(list);
        }
        if (obj.equals(btnOpen)) {
            openFileAction();
            List<Department> departments = departmentBus.getList();
            refreshDepartment(departments);
            List<Employee> employees = employeeBus.getList();
            refreshEmployee(employees);
        }
        if (obj.equals(btnSave)) {
            saveFileAction(SaveType.SAVE, departmentBus);
            flagSaveStatus = true;
        }
        if (obj.equals(btnSaveAs)) {
            saveFileAction(SaveType.SAVE_AS, departmentBus);
            flagSaveStatus = false;
        }
        if (obj.equals(btnExit)) {
            if (flagSaveStatus) {
                this.dispose();
            } else {
                int choice = JOptionPane.showConfirmDialog(this,
                        "Bạn chưa thực hiện lưu lại "
                        + "dữ liệu bạn có muốn lưu lại không?");
                switch (choice) {
                    case 0 ->
                        saveFileAction(SaveType.SAVE_AS,
                                departmentBus);
                    case 1 ->
                        this.dispose();
                    default -> {
                    }
                }

            }
        }
        if (obj.equals(menuItemInfo)) {
            InfoDialogGUI infoDialog = new InfoDialogGUI(this,
                    rootPaneCheckingEnabled);
            infoDialog.setLocationRelativeTo(null);
            infoDialog.setVisible(true);
        }
    } //ok

    private void addBtnGroupDepartment() {
        groupSortDep.add(rdbSortByNameDepartmentASC);
        groupSortDep.add(rdbSortByMemberSizeDESC);
        groupSortDep.add(rdbSortByMemberSizeASC);

    } //ok

    private void addBtnGroupEmployee() {
        groupSortEmp.add(rdbSortByNameASC);
        groupSortEmp.add(rdbSortBySalaryASC);
        groupSortEmp.add(rdbSortBySalaryDESC);
    }

    private void addActionListenerDeparment() {
        //tác vụ
        btnAddDepartment.addActionListener(this);
        btnDelDepartment.addActionListener(this);
        btnEditDepartment.addActionListener(this);
        btnListEmpDepartment.addActionListener(this);
        //tìm kiếm
        btnSearchDepartment.addActionListener(this);
        //sắp xếp
        rdbSortByNameDepartmentASC.addActionListener(this);
        rdbSortByMemberSizeASC.addActionListener(this);
        rdbSortByMemberSizeDESC.addActionListener(this);
        //làm mới dữ liệu
        btnRefreshDepartment.addActionListener(this);
        //file menu
        btnOpen.addActionListener(this);
        btnSave.addActionListener(this);
        btnSaveAs.addActionListener(this);
        btnExit.addActionListener(this);
        //thông tin menu
        menuItemInfo.addActionListener(this);
    } //ok

    private void deleteAction(BUS dataBus, EntityType entityType) {
        if (!dataBus.isEmpty()) {
            int index = -1;
            if (entityType.equals(EntityType.DEP)) {
                index = tableDepartment.getSelectedRow();
            } else if (entityType.equals(EntityType.EMP)) {
                index = tableEmployee.getSelectedRow();
            }
            if (index != -1) {
                var obj = dataBus.getList().get(index);
                int choice = JOptionPane.showConfirmDialog(panelDepartment,
                        "Bạn chắc chắn muốn xóa?");
                if (choice == 0) {
                    if (dataBus.remove(obj)) {
                        switch (entityType) {
                            case EntityType.DEP -> {
                                tableModelDepartment.removeRow(index);
                                tableModelDepartment.fireTableDataChanged();
                            }
                            case EntityType.EMP -> {
                                tableModelEmployee.removeRow(index);
                                tableModelEmployee.fireTableDataChanged();
                            }
                        }
                        var msg = "Xóa thành công.";
                        showMessage(msg);
                    }
                }
            } else {
                var msg = "Hãy chọn 1 dòng!";
                showMessage(msg);
            }
        } else {
            var msg = "Danh sách rỗng.";
            showMessage(msg);
        }
    } //ok

    private void editAction(BUS dataBus, EntityType entityType) {
        if (!dataBus.isEmpty()) {
            int index = -1;
            if (dataBus.equals(this.departmentBus)) {
                index = tableDepartment.getSelectedRow();
            } else if (dataBus.equals(employeeBus)) {
                index = tableEmployee.getSelectedRow();
            }
            if (index != -1) {
                switch (entityType) {
                    case EntityType.DEP -> {
                        //open dialog edit
                        EditDepartmentDialogGUI editDepartmentDialog
                                = new EditDepartmentDialogGUI(this,
                                        rootPaneCheckingEnabled);
                        editDepartmentDialog.setLocationRelativeTo(null);
                        editDepartmentDialog.setVisible(rootPaneCheckingEnabled);
                    }
                    case EntityType.EMP -> {
                        EditEmployeeDialogGUI editEmployeeDialogGUI
                                = new EditEmployeeDialogGUI(this,
                                        rootPaneCheckingEnabled);
                        editEmployeeDialogGUI.setLocationRelativeTo(null);
                        editEmployeeDialogGUI.setVisible(true);
                    }
                }
                flagSaveStatus = false;

            } else {
                var msg = "Hãy chọn 1 dòng!";
                showMessage(msg);
            }
        } else {
            var msg = "Danh sách rỗng.";
            showMessage(msg);
        }
    }

    private void findAction(BUS dataBus, EntityType entityType) {
        if (!dataBus.isEmpty()) {
            String value = "";
            if (dataBus.equals(this.departmentBus)) {
                value = txtDepartmentId.getText();
            } else if (dataBus.equals(employeeBus)) {
                value = txtEmployeeSearch.getText();
            }

            if (!value.isEmpty()) {
                switch (entityType) {
                    case EntityType.DEP -> {
                        findById(dataBus, value, entityType);
                    }
                    case EntityType.EMP -> {
                        int index = boxSearch.getSelectedIndex();
                        switch (index) {
                            case 0 -> {
                                findById(dataBus, value, entityType);
                            }
                            case 1 -> {
                                findByName(dataBus, value, entityType);
                            }
                        }
                    }
                }
            } else {
                var msg = "Vui lòng nhập thông tin";
                showMessage(msg);
            }
        } else {
            var msg = "Danh sách rỗng.";
            showMessage(msg);
        }
        txtDepartmentId.setText("");
    }

    private void findByName(BUS dataBus, String value, EntityType entityType) {
        List<?> list = new ArrayList<>();
        switch (entityType) {
            case EntityType.DEP -> {
                list = new ArrayList<Department>();
            }
            case EntityType.EMP -> {
                list = new ArrayList<Employee>();
            }
        }
        list = dataBus.findByName(value);
        if (!list.isEmpty()) {
            switch (entityType) {
                case EntityType.DEP -> {
                    refreshDepartment((List<Department>) list);
                }
                case EntityType.EMP -> {
                    refreshEmployee((List<Employee>) list);
                }
            }
        } else {
            var msg = "Không tìm thấy!";
            showMessage(msg);
        }

    }

    private void findById(BUS dataBus, String id, EntityType entityType) {
        Object obj = dataBus.findById(id);
        if (obj != null) {
            switch (entityType) {
                case EntityType.DEP -> {
                    tableModelDepartment.setRowCount(0);
                    showDepartment((Department) obj);
                    var msg = "Tìm thanh công id: " + id;
                    showMessage(msg);
                }
                case EntityType.EMP -> {
                    tableModelEmployee.setRowCount(0);
                    showEmployee((Employee) obj);
                    var msg = "Tìm thanh công id: " + id;
                    showMessage(msg);
                }
            }
        } else {
            var msg = "Không tồn tại id: " + id;
            showMessage(msg);
        }
    }

    private void refreshDepartment(List<Department> list) {
        tableModelDepartment.setRowCount(0);
        for (Object obj : list) {
            showDepartment((Department) obj);
        }
    }

    private void refreshEmployee(List<Employee> list) {
        tableModelEmployee.setRowCount(0);
        for (Employee obj : list) {
            showEmployee(obj);
        }
    }

    private void sortDepartment(Object obj) {
        if (!departmentBus.isEmpty()) {
            if (obj.equals(rdbSortByNameDepartmentASC)) {
                List<Department> list = departmentBus.sortByName();
                refreshDepartment(list);
            } else if (obj.equals(rdbSortByMemberSizeASC)) {
                List<Department> list = departmentBus.sortByMemberSizeASC();
                refreshDepartment(list);
            } else if (obj.equals(rdbSortByMemberSizeDESC)) {
                List<Department> list = departmentBus.sortByMemberSizeDESC();
                refreshDepartment(list);
            }
        } else {
            var msg = "Danh sách rỗng.";
            showMessage(msg);
        }
    }

    public void openFileAction() {
        var dirPart = "D:\\Code\\Java\\netBeans\\QuanLyNhanSu\\src\\data";
        File initFile = new File(dirPart);
        JFileChooser fileChooser = new JFileChooser(initFile);
        fileChooser.setFileFilter(new DataFilter());
        int actionResult = fileChooser.showOpenDialog(this);
        if (actionResult == JFileChooser.APPROVE_OPTION) {
            var file = fileChooser.getSelectedFile();
            defaultFileName = file.getName();
            if (departmentBus.readData(file)) {
                List<Department> list = departmentBus.getList();
                //employeeBus.getList().clear();
                for (int i = 0; i < list.size(); i++) {
                    //System.out.println(list.get(i).getEmpList().size());
                    employeeBus.getList().addAll(list.get(i).getEmpList());
                }
                var msg = "Mở file thành công!";
                showMessage(msg);
            } else {
                var msg = "Mở file thất bại!";
                showMessage(msg);
            }
        }

    } //cần edit lại option open

    private void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    private void saveFileAction(SaveType saveType, BUS dataBus) {
        if (!dataBus.isEmpty()) {
            var dirPart = "D:\\Code\\Java\\netBeans\\QuanLyNhanSu\\src\\Data";
            File initFile = new File(dirPart);
            JFileChooser fileChooser = new JFileChooser(initFile);

            if (saveType == SaveType.SAVE_AS) {
                fileChooser.setFileFilter(new DataFilter());
                int actionResult = fileChooser.showSaveDialog(this);
                if (actionResult == JFileChooser.APPROVE_OPTION) {
                    var file = fileChooser.getSelectedFile();
                    if (dataBus.saveData(file)) {
                        var msg = "Lưu file thành công!";
                        showMessage(msg);
                    }
                }
            } else {
                var file = new File(initFile, defaultFileName);
                if (dataBus.saveData(file)) {
                    var msg = "Lưu file thành công!";
                    showMessage(msg);
                }
            }
        } else {
            var msg = "Danh sách rỗng!";
            showMessage(msg);
        }
    }

    private void addActionListenerEmployee() {
        btnAddEmployee.addActionListener(this); //task
        btnDelEmployee.addActionListener(this); //task
        btnEditEmployee.addActionListener(this); //task
        btnExportEmp.addActionListener(this);

        btnInfoEmployee.addActionListener(this); //info of each employee
        btnRefreshEmployee.addActionListener(this); //button refresh to get new
        btnSearchEmployee.addActionListener(this); //search

        rdbSortByNameASC.addActionListener(this);
        rdbSortBySalaryASC.addActionListener(this);
        rdbSortBySalaryDESC.addActionListener(this);
    }

    private void actionPerformedEmployee(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnAddEmployee)) {
            AddEmployeeDialogGUI addEmployeeDialog
                    = new AddEmployeeDialogGUI(this, rootPaneCheckingEnabled);
            addEmployeeDialog.setLocationRelativeTo(null);
            addEmployeeDialog.setVisible(true);
            flagSaveStatus = false;
        }
        if (obj.equals(btnDelEmployee)) {
            deleteAction(employeeBus, EntityType.EMP);
            flagSaveStatus = false;
        }
        if (obj.equals(btnEditEmployee)) {
            editAction(employeeBus, EntityType.EMP); // cần edit lại dialog edit
            flagSaveStatus = false;
        }
        if (obj.equals(btnInfoEmployee)) {
            InfoEmployeeDialogGUI iedgui
                    = new InfoEmployeeDialogGUI(this, rootPaneCheckingEnabled);
            iedgui.setLocationRelativeTo(null);
            iedgui.setVisible(true);
        }
        if (obj.equals(btnRefreshEmployee)) {
            List<Employee> list = employeeBus.getList();
            refreshEmployee(list);
        }
        if (obj.equals(btnSearchEmployee)) {
            findAction(employeeBus, EntityType.EMP);
        }
        if (obj.equals(rdbSortByNameASC)
                || obj.equals(rdbSortBySalaryASC)
                || obj.equals(rdbSortBySalaryDESC)) {
            sortEmployee(obj);
        }
        if(obj.equals(btnExportEmp)){
            var msg = "Chỉ hỗ trợ xuất file nhân viên!";
            showMessage(msg);
            saveFileAction(SaveType.SAVE_AS, employeeBus);
        }
    }

    public void showEmployee(Employee emp) {
        var row = new Object[]{emp.getId(),
            emp.getFullName(), emp.getPosition(), emp.getBaseSalary()};
        tableModelEmployee.addRow(row);
        tableModelEmployee.fireTableDataChanged();
    }

    private void sortEmployee(Object obj) {
        if (!employeeBus.isEmpty()) {
            if (obj.equals(rdbSortByNameASC)) {
                List<Employee> list = new ArrayList<>();
                list = employeeBus.sortByName();
                refreshEmployee(list);
            } else if (obj.equals(rdbSortBySalaryASC)) {
                List<Employee> list = new ArrayList<>();
                list = employeeBus.sortBySalaryASC();
                refreshEmployee(list);
            } else if (obj.equals(rdbSortBySalaryDESC)) {
                List<Employee> list = new ArrayList<>();
                list = employeeBus.sortBySalaryDESC();
                refreshEmployee(list);
            }
        } else {
            var msg = "Danh sách rỗng!";
            showMessage(msg);
        }
    }
    
    private void saveEmployee(SaveType saveType, BUS dataBus) {
        if (!dataBus.isEmpty()) {
            //tinh chỉnh lại theo địa chỉ thư mục
            var dirPart = "D:\\Code\\Java\\netBeans\\QuanLyNhanSu\\src\\Data";
            File initFile = new File(dirPart);
            JFileChooser fileChooser = new JFileChooser(initFile);

            if (saveType == SaveType.SAVE_AS) {
                fileChooser.setFileFilter(new DataFilter());
                int actionResult = fileChooser.showSaveDialog(this);
                if (actionResult == JFileChooser.APPROVE_OPTION) {
                    var file = fileChooser.getSelectedFile();
                    System.out.println(dataBus.getList().getFirst().toString());
                    if (dataBus.saveData(file)) {
                        var msg = "Lưu file thành công!";
                        showMessage(msg);
                    }
                }
            } else {
                var file = new File(initFile, defaultFileName);
                if (dataBus.saveData(file)) {
                    var msg = "Lưu file thành công!";
                    showMessage(msg);
                }
            }
        } else {
            var msg = "Danh sách rỗng!";
            showMessage(msg);
        }
    }

}
