/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package staffmanagement.GUI.dialog.employee;

import exception.InvalidEmailException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import staffmanagement.BUS.BUS;
import staffmanagement.BUS.EmployeeBUS;
import staffmanagement.BUS.EntityType;
import staffmanagement.DTO.Department;
import staffmanagement.DTO.Employee;
import staffmanagement.GUI.MainPageGUI;

/**
 *
 * @author Admin
 */
public class EditEmployeeDialogGUI extends javax.swing.JDialog implements ActionListener {

    private MainPageGUI parent;
    private BUS employeeBus;
    private DefaultTableModel tableModel;
    private DefaultTableModel tableListEmpModel;
    private int indexSelected;
    private boolean flagStatus = false;

    /**
     * Creates new form EditEmployeeDialogGUI
     */
    public EditEmployeeDialogGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = (MainPageGUI) parent;
        this.employeeBus = this.parent.getEmployeeBus();
        this.tableModel = this.parent.getTableModel(EntityType.EMP);
        this.indexSelected = this.parent.getIndexSelected(EntityType.EMP);
        initComponents();
        addActionListener();
        setInfo();
    }

    public EditEmployeeDialogGUI(java.awt.Frame parent, boolean modal,
             boolean flagStatus, int index, DefaultTableModel tableModel,
             EmployeeBUS employeeBUS) {
        super(parent, modal);
        this.parent = (MainPageGUI) parent;
        this.flagStatus = flagStatus;
        this.tableModel = this.parent.getTableModel(EntityType.EMP);
        if (!flagStatus) {
            this.indexSelected = this.parent.getIndexSelected(EntityType.EMP);
            this.employeeBus = this.parent.getEmployeeBus();
        } else {
            this.employeeBus = employeeBUS;
            this.tableListEmpModel = tableModel;
            this.indexSelected = index;
        }

        initComponents();
        addActionListener();
        setInfo();
    }

    public List<Department> getDepartments() {
        List<Department> departments = new ArrayList<>();
        if (!flagStatus) {
            departments.addAll(this.parent.getDepartmentBus().getList());
            return departments;
        } else {
            var index = parent.getIndexSelected(EntityType.DEP);
            var departmentTmp = parent.getDepartmentBus().getList().get(index);
            departments.add(departmentTmp);
            return departments;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeader = new javax.swing.JLabel();
        labelSex = new javax.swing.JLabel();
        txtBaseSalary = new javax.swing.JTextField();
        labelBaseSalary = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        labelPosition = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        labelAdress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        boxSex = new javax.swing.JComboBox<>();
        labelEmail = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        labelDepartment = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelDob = new javax.swing.JLabel();
        boxDeparment = new javax.swing.JComboBox<>();
        labelCCCD = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setText("CHỈNH SỬA NHÂN VIÊN");

        labelSex.setText("Giới tính:");

        labelBaseSalary.setText("Lương cơ bản:");

        btnEdit.setText("Sửa");

        labelPosition.setText("Vị trí làm việc:");

        btnCancel.setText("Hủy");

        labelAdress.setText("Địa chỉ:");

        labelID.setText("Mã nhân viên:");

        labelName.setText("Họ tên:");

        boxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        labelEmail.setText("Email liên hệ:");

        labelDepartment.setText("Phòng ban:");

        labelDob.setText("Ngày sinh:");

        boxDeparment.setModel(new BoxDepartmentModel(getDepartments())
        );

        labelCCCD.setText("CCCD:");

        txtID.setText("id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelBaseSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxDeparment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBaseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnEdit)
                        .addGap(110, 110, 110)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(boxSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDob, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(txtID))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCCCD)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSex)
                    .addComponent(boxSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAdress))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepartment)
                    .addComponent(boxDeparment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosition)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBaseSalary)
                    .addComponent(txtBaseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnCancel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditEmployeeDialogGUI dialog = new EditEmployeeDialogGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDeparment;
    private javax.swing.JComboBox<String> boxSex;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel labelAdress;
    private javax.swing.JLabel labelBaseSalary;
    private javax.swing.JLabel labelCCCD;
    private javax.swing.JLabel labelDepartment;
    private javax.swing.JLabel labelDob;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPosition;
    private javax.swing.JLabel labelSex;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBaseSalary;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosition;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        var obj = e.getSource();
        if (obj.equals(btnCancel)) {
            this.dispose();
        }
        if (obj.equals(btnEdit)) {
            int choice = JOptionPane.showConfirmDialog(parent,
                    "Bạn có muốn sửa không?");
            if (choice == 0) {
                Employee emp = editEmployee();
                tableModel.removeRow(indexSelected);
                tableModel.fireTableDataChanged();
                this.parent.showEmployee(emp);
                JOptionPane.showMessageDialog(parent,
                        "Sửa thông tin thành công!");
            }

        }
    }

    private void addActionListener() {
        btnCancel.addActionListener(this);
        btnEdit.addActionListener(this);
    }

    private void setInfo() {
        Employee emp = (Employee) employeeBus.getList().get(indexSelected);
        txtID.setText(emp.getId());
        txtName.setText(emp.getFullName());
        txtCCCD.setText(emp.getCccd());
        setSex(emp);

        //format form dob
        var format = "dd/MM/yyyy";
        SimpleDateFormat dateFormat = new SimpleDateFormat(format);
        Date date = emp.getDob();
        txtDob.setText(dateFormat.format(date));

        txtEmail.setText(emp.getEmail());
        txtAddress.setText(emp.getAddress());
        setDepartment(emp);
        txtPosition.setText(emp.getPosition());
        txtBaseSalary.setText(String.valueOf(emp.getBaseSalary()));

    }

    private void setSex(Employee emp) {
        boolean sex = emp.getSex();
        if (sex) {
            boxSex.setSelectedIndex(0);
        } else {
            boxSex.setSelectedIndex(1);
        }
    }

    private void setDepartment(Employee emp) {
        Department dep = emp.getDepartment();
        for (int i = 0; i < boxDeparment.getItemCount(); i++) {
            if (boxDeparment.getItemAt(i).compareToIgnoreCase(dep.getName()) == 0) {
                boxDeparment.setSelectedIndex(i);
                break;
            }
        }
    }

    public Date getDob() {
        var format = "dd/MM/yyyy";
        SimpleDateFormat dateFormat = new SimpleDateFormat(format);
        Date date = null;
        try {
            date = dateFormat.parse(txtDob.getText());
        } catch (ParseException ex) {
            ex.getMessage();
            JOptionPane.showMessageDialog(parent,
                    "Định dạng ngày sinh nhập vào không hơp lệ! 'dd/MM/yyyy'"
                    + date);
        }
        return date;
    }

    public boolean getSex() {
        var obj = boxSex.getSelectedItem();
        return obj.equals("Nam");
    }

    public Department getDepartment() {
        var obj = boxDeparment.getSelectedItem();
        List<Department> departments = getDepartments();
        for (var department : departments) {
            if (department.getName().equalsIgnoreCase(obj.toString())) {
                return department;
            }
        }
        return null;
    }

    private Employee editEmployee() {
        Employee emp = new Employee();
        var name = txtName.getText();
        var cccd = txtCCCD.getText();
        var sex = getSex();
        var dob = getDob();
        var email = txtEmail.getText();
        var address = txtAddress.getText();
        var department = getDepartment();
        var position = txtPosition.getText();
        var baseSalary = Long.parseLong(txtBaseSalary.getText());

        if (!(name.isEmpty() && cccd.isEmpty() && email.isEmpty() && address.isEmpty()
                && position.isEmpty())) {
            emp = this.parent.getEmployeeBus().getList().get(indexSelected);
            emp.setFullName(name);
            emp.setCccd(cccd);
            emp.setDob(dob);
            emp.setSex(sex);
            try {
                emp.setEmail(email);
            } catch (InvalidEmailException ex) {
                Logger.getLogger(EditEmployeeDialogGUI.class.getName())
                        .log(Level.SEVERE, null, ex);
            }
            emp.setPosition(position);
            emp.setAddress(address);
            emp.setDepartment(department);
            emp.setBaseSalary(baseSalary);
        }
        return emp;
    }
}
